build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/weatherforce-platform/weather-notebook:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/weatherforce-platform/weather-notebook:$CI_COMMIT_SHA
  only:
    - master

