image: docker:latest

services:
  - docker:dind


before_script:
  - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.gitlab.com


stages:
  - build
  - release


build:
  stage: build
  script:
    - make build


release:
  stage: release
  script:
    - docker push registry.gitlab.com/weatherforce-platform/weather-notebook
